// <auto-generated />
namespace ActionPlatform.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddAccessTolken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAccessTolken));
        
        string IMigrationMetadata.Id
        {
            get { return "201411161331428_AddAccessTolken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
