// <auto-generated />
namespace ActionPlatform.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201411161336450_addUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
